/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gif_xz_gifnativedemo_NdkJniUtils */

#ifndef _Included_com_gif_xz_gifnativedemo_NdkJniUtils
#define _Included_com_gif_xz_gifnativedemo_NdkJniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gif_xz_gifnativedemo_NdkJniUtils
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gif_xz_gifnativedemo_NdkJniUtils_stringFromJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
